### ISSUE TITLE
Parsing issues with matchms 0.19

### ISSUE THREAD

**Issue by ADablanc** [matchms/matchms#421] opened 2023-05-23 14:29 UTC
Hello !

There is some issus about "bad peaks pattern" and "could not convert string to float (for metadata_filtering.get("parent"))" with the 0.19 which worked with the 0.18

**Comment by hechth** [comment] 2023-05-23 15:08
Hi @ADablanc could you provide an example spectrum where the reading fails? Then we can work on a fix for this which will come with the next release. Thank you very much!

**Comment by ADablanc** [comment] 2023-05-23 15:44
Hi @hechth !
Yes sorry, there is a exemple for the first issus:
NAME: 3-Des-Microcystein_LR
PRECURSORMZ: 981.54
PRECURSORTYPE: M+H
FORMULA: C48H72N10O12
Ontology: 
INCHIKEY: IYDKWWDUBYWQGF-NNAZGLEUSA-N
INCHI: N/A
SMILES: CC(C)CC1NC(=O)C(C)NC(=O)C(=C)N(C)C(=O)CCC(NC(=O)C(C)C(NC(=O)C(CCCNC(N)=N)NC(=O)C(C)C(NC1=O)C(O)=O)\C=C\C(\C)=C\C(C)C(O)Cc1ccccc1)C(O)=O
RETENTIONTIME: CCS: 
IONMODE: Positive
INSTRUMENTTYPE: LC-ESI-qTof
INSTRUMENT: qTof
COLLISIONENERGY: 
Comment: DB#=CCMSLIB00000001547; origin=GNPS
Num Peaks: 218
289.286377	8068.0
295.545288	22507.0
298.489624	3925.0
317.324951	18742.0
319.655945	8604.0
324.482422	8041.0
325.316284	9738.0
339.789429	16145.0
343.947021	18094.0
347.020508	13981.0
347.913391	6765.0
361.147705	11763.0
361.84436	24296.0
364.232727	2346.0
364.858154	10782.0
365.845886	10242.0
368.22168	12761.0
368.965698	19147.0
375.069519	15644.0
375.751953	25393.0
382.750549	12765.0
384.197083	17912.0
390.574219	7993.0
394.049194	16135.0
397.106262	13986.0
404.420715	12326.0
411.092712	2348.0
413.784546	8715.0
427.667358	68137.0
436.192749	14879.0
443.266113	44427.0
446.267273	23472.0
447.747498	29292.0
455.25	70939.0
456.107544	105392.0
456.822144	3.0
457.543213	12862.0
464.285461	8617.0
469.872314	87594.0
471.062195	31482.0
475.257324	15449.0
476.143616	23143.0
476.975159	28430.0
478.891113	27890.0
479.975952	33235.0
483.242432	13564.0
487.210388	32885.0
488.160156	20786.0
491.191956	55073.0
494.279602	7435.0
495.653992	32208.0
498.412964	11684.0
503.028198	30643.0
503.699951	2.0
504.344543	36421.0
505.154541	9667.0
510.176514	38891.0
512.168701	10175.0
513.265381	16524.0
514.957397	11384.0
515.922852	78764.0
520.973389	28857.0
521.82373	5810.0
523.168945	58926.0
529.036865	20722.0
530.991211	31845.0
532.376709	3005.0
534.575195	12906.0
538.003174	220949.0
539.217773	272296.0
540.672852	43876.0
548.061401	13655.0
554.117432	76225.0
556.030396	214421.0
557.288818	52970.0
557.996094	6202.0
559.942261	18112.0
561.328735	14656.0
564.123047	25971.0
564.94873	34630.0
566.439941	35564.0
571.33374	61305.0
572.047363	17235.0
575.219238	42127.0
575.888916	6.0
577.102905	29550.0
579.645874	7151.0
580.942627	17609.0
582.110107	102075.0
583.458984	10113.0
585.237061	36774.0
598.172485	26085.0
599.352783	764523.0
600.382812	114267.0
601.06665	4.0
602.267578	27144.0
609.302002	10247.0
613.415771	8621.0
622.208984	23787.0
623.023193	63940.0
623.991455	19154.0
625.216187	23050.0
638.299561	12481.0
640.265625	17392.0
641.235107	65873.0
646.095947	8409.0
649.2771	5446.0
651.526611	17521.0
657.128906	12911.0
658.094971	14824.0
659.420898	41969.0
663.387695	18284.0
668.33252	65700.0
669.357178	5671.0
680.219727	44374.0
681.987793	24446.0
685.957764	19166.0
691.648682	29177.0
693.22583	33545.0
694.307861	22539.0
696.332397	121211.0
697.127808	9503.0
709.464478	20171.0
710.79541	22346.0
711.744873	32675.0
714.071777	50487.0
715.578979	54567.0
716.216553	8.0
723.267822	14415.0
724.081909	88510.0
725.488892	8470.0
728.352051	21518.0
735.806396	52022.0
738.34668	2697.0
744.365234	16205.0
747.456055	19268.0
753.27124	14114.0
761.609131	12373.0
764.462158	19876.0
765.280029	18361.0
769.275635	41999.0
770.328613	16548.0
771.386353	13776.0
787.432617	33003.0
796.139526	9637.0
797.232788	11322.0
806.556885	18639.0
808.442383	6355.0
811.637329	14687.0
812.300049	9904.0
813.149292	15959.0
817.219238	7640.0
820.274048	6246.0
821.288208	15591.0
823.361328	13693.0
824.618286	6895.0
828.517456	32132.0
830.409302	102583.0
831.306763	65294.0
832.105469	9727.0
833.18457	4115.0
835.212891	7606.0
836.078247	8740.0
838.518677	26160.0
839.455811	72006.0
845.612915	21577.0
847.433594	196462.0
848.125854	39637.0
851.380859	246170.0
852.370605	276882.0
853.270508	44216.0
865.5979	44697.0
866.295654	111012.0
867.19043	4120.0
868.372192	78023.0
869.331177	8584.0
871.557007	5374.0
877.137451	30131.0
880.216553	5692.0
883.442261	49241.0
884.216553	8.0
888.167114	41037.0
889.282959	24795.0
892.127808	14925.0
893.467896	23506.0
895.607422	13123.0
899.010132	28633.0
901.351196	13472.0
902.325562	3774.0
909.424438	244136.0
910.515381	43770.0
911.526367	15208.0
914.30896	6532.0
915.217773	28455.0
918.666138	5610.0
919.39624	85829.0
920.06665	3.0
921.123901	16163.0
922.205688	37863.0
925.063721	43395.0
931.132812	61732.0
932.351929	136657.0
933.524048	25202.0
935.493286	33896.0
936.552002	103130.0
937.588623	67605.0
938.471069	35379.0
939.61792	77289.0
946.257812	38584.0
949.370239	85420.0
950.284546	5976.0
951.551758	29995.0
953.396606	545281.0
954.491577	123937.0
963.686768	261578.0
964.524658	318164.0
965.192139	124405.0
982.221924	27147.0


and a exemple for the second issu:
Name: Triacetin (C2:0)
Compound Id: 5541
Precursor Type: [M+NH4]+
Comment: 0.72790725_236.113055066092m/z
Formula: C9H14O6
Num Peaks: 110
49.5027732215 0.0
49.5031037136 0.0
49.503434209 0.0
57.0315860185 0.0
57.0319947042 0.0
57.0324033944 0.0
57.034446911 3737.36669922
57.0364713016 0.0
57.0368800401 0.0
57.0372887829 0.0
59.8905044188 0.0
59.8909442169 0.0
59.8913840198 0.0
59.89314328 1246.35253906
59.8948968602 0.0
59.8953367068 0.0
59.8957765582 0.0
60.752456319 0.0
60.7529056456 0.0
60.7533549772 0.0
60.7551523536 1272.62255859
60.7568653146 0.0
60.7573146911 0.0
60.7577640726 0.0
73.3018798444 0.0
73.3024753548 0.0
73.3030708724 0.0
73.3060485695 2677.84350586
73.3088681969 0.0
73.3094637944 0.0
73.3100593991 0.0
96.7102347645 0.0
96.71113722 0.0
96.712039688 0.0
96.7129421687 0.0
96.7138446621 0.0
96.7147471681 0.0
96.7156496867 0.0
96.7165522179 0.0
96.7174547618 0.0
96.7182125688 0.0
96.7191151379 0.0
96.7200177197 0.0
96.7209203141 0.0
118.079303808 0.0
118.080521334 0.0
118.081738878 0.0
118.086609245 2361.35766602
118.092619785 0.0
118.093837518 0.0
118.095055269 0.0
129.446174364 0.0
129.447571863 0.0
129.448969385 0.0
129.454559698 1474.59936523
129.460217638 0.0
129.461615364 0.0
129.463013112 0.0
159.045024748 0.0
159.046928004 0.0
159.048831294 0.0
159.06596244 314151.0
159.081268747 0.0
159.083172652 0.0
159.085076591 0.0
159.086980565 0.0
177.07707177 0.0
177.07930771 0.0
177.081543692 0.0
177.090488045 2219.77270508
177.101784232 0.0
177.104020638 0.0
177.106257086 0.0
200.128339924 0.0
200.131026377 0.0
200.133712883 0.0
200.14445945 2634.81518555
200.158013762 0.0
200.16070081 0.0
200.163387911 0.0
219.542133044 0.0
219.545219733 0.0
219.548306486 0.0
219.560654151 1563.37365723
219.575963271 0.0
219.579050611 0.0
219.582138015 0.0
236.100215645 0.0
236.103657974 0.0
236.107100379 0.0
236.131199323 21526.5488281
236.148957011 7795.94384766
236.168318727 32249.9414062
236.183394891 0.0
236.186839104 0.0
236.190283392 0.0
236.204061297 2359.49780273
236.221275624 0.0
236.224720665 0.0
236.228165782 0.0
241.489059709 0.0
241.492620629 0.0
241.496181627 0.0
241.510426408 1590.36975098
241.524672449 0.0
241.528234156 0.0
241.531795942 0.0
262.619477085 0.0
262.623515458 0.0
262.627553925 0.0

Name: Triacetin (C2:0)
Compound Id: 5541
Precursor Type: [M+NH4]+
Comment: 0.74684692_236.11319115071m/z
Formula: C9H14O6
Num Peaks: 137
49.5028097575 0.0
49.5031402496 0.0
49.503470745 0.0
51.4876603996 0.0
51.4880109665 0.0
51.488361537 0.0
51.4897638548 2909.76586914
51.4911444974 0.0
51.4914951001 0.0
51.4918457064 0.0
54.7181468111 0.0
54.7185308837 0.0
54.7189149604 0.0
54.7204513074 2444.80615234
54.7219770434 0.0
54.7223611565 0.0
54.7227452736 0.0
56.3074252922 0.0
56.3078262188 0.0
56.3082271496 0.0
56.3098309157 3174.78417969
56.3114299118 0.0
56.3118308812 0.0
56.3122318549 0.0
57.0315851994 0.0
57.0319938852 0.0
57.0324025753 0.0
57.0344460919 14590.2880859
57.03688648 0.0
57.0372952228 0.0
57.0377039701 0.0
58.8149639816 0.0
58.8153919859 0.0
58.8158199948 0.0
58.8175320774 2741.03173828
58.8192438144 0.0
58.8196718654 0.0
58.8200999211 0.0
58.877930361 0.0
58.8783590528 0.0
58.8787877492 0.0
58.8805025819 2735.61669922
58.8822030606 0.0
58.8826317992 0.0
58.8830605425 0.0
61.0265668022 0.0
61.0270191732 0.0
61.0274715493 0.0
61.029281104 4157.06933594
61.0314604304 0.0
61.0319128568 0.0
61.0323652882 0.0
73.3120033869 0.0
73.3125990206 0.0
73.3131946617 0.0
73.3161729756 4617.62792969
73.3185267128 0.0
73.3191224264 0.0
73.3197181473 0.0
77.6123391297 0.0
77.6129879328 0.0
77.613636744 0.0
77.6162320703 2777.62158203
77.6185605685 0.0
77.6192094529 0.0
77.6198583455 0.0
117.046376744 0.0
117.047578329 0.0
117.048779932 0.0
117.054788226 13636.6923828
117.061971691 0.0
117.063173516 0.0
117.06437536 0.0
121.017292106 0.0
121.018555354 0.0
121.019818622 0.0
121.024871891 3098.5324707
121.029898178 0.0
121.031161624 0.0
121.03242509 0.0
125.007886699 0.0
125.009212944 0.0
125.01053921 0.0
125.015844485 2957.74853516
125.021121588 0.0
125.022448044 0.0
125.023774521 0.0
129.246564784 0.0
129.247959052 0.0
129.249353342 0.0
129.254930729 2714.36083984
129.260491896 0.0
129.261886389 0.0
129.263280905 0.0
142.688999876 0.0
142.690617223 0.0
142.692234598 0.0
142.698704371 2978.76757812
142.705256373 0.0
142.706873995 0.0
142.708491645 0.0
159.045022267 0.0
159.046925522 0.0
159.048828812 0.0
159.065959958 790183.1875
159.083077446 0.0
159.084981385 0.0
159.086885359 0.0
159.088789366 0.0
159.090693408 0.0
159.092597484 0.0
159.094501594 0.0
159.096405738 0.0
159.098513522 0.0
159.100417734 0.0
159.102321981 0.0
159.104226262 0.0
201.470196737 0.0
201.472910254 0.0
201.475623826 0.0
201.48647866 2934.0559082
201.497517331 0.0
201.500231396 0.0
201.502945516 0.0
236.104195539 0.0
236.107638019 0.0
236.111080575 0.0
236.128294482 13998.8896484
236.144500467 0.0
236.147943776 0.0
236.168605209 26642.953125
236.185825142 0.0
236.189269355 0.0
236.192713642 0.0
262.621916705 0.0
262.625955079 0.0
262.629993546 0.0

thank you very much !

**Comment by hechth** [comment] 2023-05-23 16:02
Why are there so many peaks with an intensity of 0? Just curious.

**Comment by ADablanc** [comment] 2023-05-23 16:25
I don't know. It's not our exp MSP. I have dowloaded GNPS + EMBL MSP DB. Just work with 0.18 but not with 0.19

**Comment by hechth** [comment] 2023-05-24 10:44
Thanks @ADablanc - we will look into it. Version 0.18 is still available, so I'd advice to use it in the meantime.

**Comment by hechth** [comment] 2023-05-25 09:41
@ADablanc I can't reproduce your error - which code are you executing on the spectra? can you try using the development version of matchms or provide me the exact function call which fails for you? thank you very much.

**Comment by ADablanc** [comment] 2023-05-25 12:01
Hi @hechth ! I join you my previous py file where I had the error: https://drive.google.com/file/d/1I_hj5Jw7kh2-4HpS-lKc0DJIwvGR1IMp/view?usp=sharing. (on a new multithreaded version, but still not work with 0.19 :( ) ... the error is with the function "load_from_msp" (line 64 of my code)

**Comment by hechth** [comment] 2023-05-26 09:08
thanks for providing the code, I will look into it with the spectra you provided previously.

**Comment by ADablanc** [comment] 2023-05-26 09:43
Thanks you very much @hechth ! To complete, here is the file causing the issue. and the full error message. 
https://drive.google.com/drive/folders/1JVWzRaD26rPhTk7H8rj9fEKrTHz_ofTU?usp=sharing

**Comment by ADablanc** [comment] 2023-06-09 10:12
Hi. i have news about this issue. this error apear when matchms try to read this spectrum:
NAME: phenazine-1-carboxamide
PRECURSORMZ: 224.0
PRECURSORTYPE: M+H
FORMULA: C13H9N3O
Ontology: 
INCHIKEY: KPZYYKDXZKFBQU-UHFFFAOYSA-N
INCHI: InChI=1S/C13H9N3O/c14-13(17)8-4-3-7-11-12(8)16-10-6-2-1-5-9(10)15-11/h1-7H,(H2,14,17)
SMILES: C1=CC=C2C(=C1)N=C3C=CC=C(C3=N2)C(=O)N
RETENTIONTIME: CCS: 
IONMODE: Positive
INSTRUMENTTYPE: DI-ESI-Ion Trap
INSTRUMENT: Ion Trap
COLLISIONENERGY: 
Comment: DB#=CCMSLIB00000006832; origin=GNPS
Num Peaks: 312
78.909088	0.066286
79.0	0.102231
79.090912	0.028708
79.36364	0.001307
79.454544	0.000295
79.727272	3e-06
79.818184	2e-06
109.909096	0.000642
110.0	0.022613
110.090912	0.090857
110.181816	0.117288
110.272728	0.039857
110.545456	0.00086
110.636368	0.000278
110.909096	1e-06
111.0	1e-06
118.0	0.04606
118.090912	0.098619
118.181824	0.047114
118.545456	0.000201
118.636368	1.2e-05
118.909096	1e-06
126.818184	0.002632
126.909096	0.014997
127.0	0.025161
127.090912	0.013442
127.36364	5e-06
127.454544	6.1e-05
127.545456	4e-06
137.0	0.028562
137.090912	0.110638
137.181824	0.125281

...

**Closed as completed** 2023-06-19 13:12 UTC
